download_url: https://galaxy.ansible.com/download/ansible-network-2.0.0.tar.gz
format_version: 1.0.0
name: network
namespace: ansible
server: https://galaxy.ansible.com/api/
signatures: []
version: 2.0.0
version_url: https://galaxy.ansible.com/api/v2/collections/ansible/network/versions/2.0.0/
