---
- name: Change to Secondary ISP config
  hosts: rtr1

  tasks:

  - ansible.builtin.debug:
        msg: " Caution you have switched over to the secondary ISP"
    run_once: true

# Router Checks
  - name: reset IP SLA counters 
    cisco.ios.ios_config:
      lines: ip sla restart 1
    when: inventory_hostname == "rtr1"

  - name: Grab Current Time
    set_fact: current_time="{{ lookup('pipe','date +%Y-%m-%d\ %H:%M:%S') }}"

  - name: Check IP SLA
    cisco.ios.ios_command:
      commands:
        - show ip sla statistics
    register: stats

  - name: Traceroute
    cisco.ios.ios_command:
      commands:
        - traceroute 192.168.40.4
    register: trace

  - name: Show ip route
    cisco.ios.ios_command:
      commands:
        - sh ip route 192.168.40.4
    register: route

#Add SNOW Incident 

  - name: Create SNOW incident if router fails over to Secondary ISP
    block:
      - name: Create SNOW ticket
        servicenow.itsm.incident:
          instance:
            host: "{{ SN_HOST }}"
            username: "{{ SN_USERNAME }}"
            password: "{{ SN_PASSWORD }}"
          state: new
          impact: high
          urgency: high
          description: "{{inventory_hostname}} ipsla has failed and Primary ISP link is down!   traceroute: {{trace.stdout_lines}}   route: {{route.stdout_lines}}"
          short_description: "Primary ISP link is down {{inventory_hostname}} Cat8000v @ {{ current_time }}"
        register: snow_var
        delegate_to: localhost
        when: "'Number of failures: 0' not in snow_var.stdout"

      - name: Show incident number
        ansible.builtin.debug:
          msg: 
          - "{{ snow_var.record.number }}"

# Update incident ID 

  - name: Update job-template - Network-EDA-Primary
    ansible.controller.job_template:
        name: "Network-EDA-Primary"
        organization: "Red Hat network organization"
        credentials:
          - "Workshop Credential"
        execution_environment: "Validated Network"
        state: "present"
        extra_vars:
          incident_num: "{{ snow_var.record.number }}"
          SN_HOST: https://ven05430.service-now.com
          SN_USERNAME: admin
          SN_PASSWORD: "{{ SN_PASSWORD }}"
    delegate_to: localhost

      
          