- name: Resolve SNOW incident if configuration is compliant
  block:
    - name: Resolve ticket
      servicenow.itsm.incident:
        instance:
          host: "{{ SN_HOST }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
        number: "{{ incident_num }}"
        state: resolved
        close_code: "Solved (Permanently)"
        close_notes: "Problem is fixed"
        short_description: "{{inventory_hostname.split('1')[0] | capitalize }} CSR 1000v is now compliant, closing ticket"

    - name: Close ticket
      servicenow.itsm.incident:
        instance:
          host: "{{ SN_HOST }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
        close_code: "Solved (Permanently)"
        close_notes: "Now you are close"
        state: closed
        number: "{{ incident_num }}"
        short_description: "Banner on {{inventory_hostname.split('1')[0] | capitalize }} CSR 1000v has been updated, marking resolved"
