---
- name: Check/Apply EOS logging configuration
  arista.eos.eos_logging_global:
    config: "{{ logging_eos }}"   
    state: replaced
  register: logging_diff

- ansible.builtin.debug:
    msg:
    - "current logging config"
    - "{{ logging_diff.before }}"
    - "replace commands (remediation)"
    - "{{ logging_diff.commands | default ('no diff found') }}"