---
- name: Check/Apply Junos logging configuration
  junipernetworks.junos.junos_logging_global:
    config: "{{ logging_junos }}"   
    state: replaced
  register: logging_diff

- ansible.builtin.debug:
    msg:
    - "current logging config"
    - "{{ logging_diff.before }}"
    - "replace commands (remediation)"
    - "{{ logging_diff.commands | default ('no diff found') }}"