download_url: https://galaxy.ansible.com/download/frr-frr-2.0.2.tar.gz
format_version: 1.0.0
name: frr
namespace: frr
server: https://galaxy.ansible.com/api/
signatures: []
version: 2.0.2
version_url: https://galaxy.ansible.com/api/v2/collections/frr/frr/versions/2.0.2/
