---
- name: Compare intended state in NetBox to actual device state and show delta
  hosts: sites_rtp
  gather_facts: false

  roles:
    - role: ACTUAL_STATE
    - role: INTENDED_STATE
    - role: COMPARE_STATES