---
- name: Setup Netbox
  hosts: localhost
   
  tasks:
    - name: "SETUP SITES"
      netbox.netbox.netbox_site:
        netbox_url: "https://netbox-demo.netboxlabs.com/"
        netbox_token: "{{ netbox_api_key }}"
        data: "{{ item }}"
      loop: "{{ site_list }}"

    - name: "SETUP MANUFACTURERS"
      netbox.netbox.netbox_manufacturer:
        netbox_url: "https://netbox-demo.netboxlabs.com/"
        netbox_token: "{{ netbox_api_key }}"
        data:
          name: "{{ manufacturer }}"
      loop: "{{ manufacturers }}"
      loop_control:
        loop_var: manufacturer

    - name: "SETUP DEVICE TYPES"
      netbox.netbox.netbox_device_type:
        netbox_url: "https://netbox-demo.netboxlabs.com/"
        netbox_token: "{{ netbox_api_key }}"
        data:
          model: "{{ device_type.model }}"
          manufacturer: "{{ device_type.manufacturer }}"
          slug: "{{ device_type.slug }}"
          part_number: "{{ device_type.part_number }}"
          is_full_depth: "{{ device_type.Full_depth }}"
      loop: "{{ device_types }}"
      loop_control:
        loop_var: device_type
        label: "{{ device_type['model'] }}"

    - name: "SETUP PLATFORMS"
      netbox.netbox.netbox_platform:
        netbox_url: "https://netbox-demo.netboxlabs.com/"
        netbox_token: "{{ netbox_api_key }}"
        data:
          name: "{{ platform.name }}"
          slug: "{{ platform.slug }}"
      loop: "{{ platforms }}"
      loop_control:
        loop_var: platform
        label: "{{ platform['name'] }}"