---
- name: Gather configuration information from Cisco IOS-XE devices
  hosts: cisco
  gather_facts: no

  tasks:
    - name: copy running config to startup config
      cisco.ios.ios_command:
        commands:
          - command: 'copy running-config startup-config'
            prompt: Destination
            answer: "\r"
      register: result

    - name: run multiple commands on remote nodes
      ios_command:
        commands:
          - show version
          - show interfaces

    - name: Backup cisco ios configuration
      cisco.ios.ios_config:
        backup: true
        backup_options:
          dir_path: /tmp/
          filename: "{{ inventory_hostname }}.txt"
      register: config_output

    - name: Check for backup on EE
      ansible.builtin.command: cat /tmp/"{{ inventory_hostname }}.txt"

        # - name: Authenticate the trustpoint with the CA Cert
        #   ansible.netcommon.cli_command:
        #     command: "{{ item }}"
        #     sendonly: true
        #   loop: "{{ cacert_var }}"

    - name: Gather network information as structured data
      tags:
        - always
      cisco.ios.ios_facts:
        gather_network_resources:
          - 'all'
          # - 'ntp_global'
          # - 'logging_global'
          # - 'hostname'
          # - 'snmp_server'
          # - 'vlans'
          # - 'interfaces'
          # - 'l2_interfaces'
          # - 'l3_interfaces'
          # - 'lag_interfaces'
          # - 'lldp_interfaces'
          # - 'lldp_global'
          # - 'lacp'
          # - 'lacp_interfaces'
          # - 'service'
          # - 'bgp_global'
          # - 'bgp_address_family'
          # - 'ospf_interfaces'
          # - 'ospfv2'
          # - 'ospfv3'
          # - 'prefix_lists'
          # - 'static_routes'
          # - 'acl_interfaces'

    - name: Print out
      ansible.builtin.debug:
        msg: "{{ ansible_network_resources | to_nice_yaml }}"

