- name: Cisco IOS XE STIG
  hosts: cisco,juniper
  gather_facts: false

  tasks:

    - name: Run Cisco STIG
      when: ansible_network_os == 'ios'
      vars:
        ignore_all_errors: False
      ansible.builtin.include_role:
        name: iosxeSTIG
      # notify: cisco_stig
      register: cisco_stig_reg

    - name: Debug
      ansible.builtin.debug:
        var: cisco_stig_reg

    # - name: Run JunOS STIG
    #   when: ansible_network_os == 'junos'
    #   ansible.builtin.import_role:
    #     name: junosSTIG

  handlers:
   - name: Cisco_stig
     ansible.builtin.debug:
       msg: "Woot!"
