- name: Cisco IOS XE STIG
  hosts: cisco,juniper
  gather_facts: false
  vars:
    change_fact: false
  tasks:

    - name: Run Cisco STIG
      when: ansible_network_os == 'ios'
      vars:
        ignore_all_errors: False
      ansible.builtin.include_role:
        name: iosxeSTIG
      # notify: cisco_stig
      register: cisco_stig_reg

    - name: Force all notified handlers to run at this point, not waiting for normal sync points
      ansible.builtin.meta: flush_handlers

    - name: Debug
      ansible.builtin.debug:
        var: change_fact

    # - name: Run JunOS STIG
    #   when: ansible_network_os == 'junos'
    #   ansible.builtin.import_role:
    #     name: junosSTIG


