---
- name: Gather configuration information from network devices
  hosts: cisco,juniper
  gather_facts: false

  tasks:

    - name: Print network OS play
      ansible.builtin.debug:
        msg: "{{ ansible_network_os }}"

    # This task will backup the configuration
    - name: Backup cisco ios configuration
      cisco.ios.ios_config:
        backup: true
        backup_options:
          dir_path: /tmp/
          filename: "{{ inventory_hostname }}.txt"
      register: config_output

    - name: Print out
      ansible.builtin.debug:
        msg: "{{ ansible_network_resources }}"
        verbosity: 2

    - name: GitOps functions
      delegate_to: localhost
      when: ansible_network_resources is defined
      block:
        - name: Retrieve a repository from a distant location and make it available locally
          ansible.scm.git_retrieve:
            origin:
              url: "http://gitea:gitea@ansible-1:3000/gitea/network-demos-repo.git"
              token: "{{ password }}"
          register: repository

        - name: Debug repository data
          ansible.builtin.debug:
            var: repository
            verbosity: 2

        - name: Create a host_vars directory if it does not exist
          ansible.builtin.file:
            path: "{{ repository['path'] }}/base_configuration/host_vars"
            state: directory
            mode: '0755'

        - name: Add network facts to the repository
          ansible.builtin.copy:
            content: "{{ ansible_network_resources | to_nice_yaml }}"
            dest: "{{ repository['path'] }}/base_configuration/host_vars/{{ inventory_hostname }}"
          register: result

        - name: Set date_time variable
          ansible.builtin.set_fact:
            date_time: "{{ lookup('pipe', 'date +%Y-%m-%d%H:%M:%S') }}"

        - name: Publish the changes
          when: result.changed
          ansible.scm.git_publish:
            commit:
              message: "Update at {{ date_time }}"
            include: "--all"
            path: "{{ repository['path'] }}"
            token: "{{ password }}"
            user:
              name: "{{ username }}"
              email: "{{ email }}"
      ### End of GitOps Block

...
