---
- name: Gather configuration information from network devices
  hosts: cisco,juniper
  gather_facts: false

  tasks:
    - name: Gather network information as structured data
      ansible.builtin.include_role:
        name: "roles/gather_facts"

    - name: Print out
      tags:
        - always
      ansible.builtin.debug:
        msg: "{{ ansible_network_resources }}"
        verbosity: 2

    - name: GitOps functions
      tags:
        - gitops
        - never
      delegate_to: localhost
      when: ansible_network_resources is defined
      block:
        - name: Retrieve a repository from a distant location and make it available locally
          ansible.scm.git_retrieve:
            origin:
              url: "http://gitea:gitea@ansible-1:3000/gitea/network-demos-repo.git"
              token: "{{ password }}"
          register: repository

        - name: Debug repository data
          ansible.builtin.debug:
            var: repository
            verbosity: 2

        - name: Create a host_vars directory if it does not exist
          ansible.builtin.file:
            path: "{{ repository['path'] }}/host_vars"
            state: directory
            mode: '0755'

        - name: Add network facts to the repository
          ansible.builtin.copy:
            content: "{{ ansible_network_resources | to_nice_yaml }}"
            dest: "{{ repository['path'] }}/host_vars/{{ inventory_hostname }}"
          register: result

        - name: Set date_time variable
          ansible.builtin.set_fact:
            date_time: "{{ lookup('pipe', 'date +%Y-%m-%d%H:%M:%S') }}"

        - name: Publish the changes
          when: result.changed
          ansible.scm.git_publish:
            commit:
              message: "Update at {{ date_time }}"
            include: "--all"
            path: "{{ repository['path'] }}"
            token: "{{ password }}"
            user:
              name: "{{ username }}"
              email: "{{ email }}"
      ### End of GitOps Block

...
