- name: Cisco IOS XE STIG
  hosts: cisco
  gather_facts: false
  vars:
    change_fact: true
    changed_rules: []
  tasks:

    # - name: Run Cisco STIG
    #   when: ansible_network_os == 'ios'
    #   vars:
    #     ignore_all_errors: False
    #   ansible.builtin.include_role:
    #     name: iosxeSTIG
    #   # notify: cisco_stig
    #   register: cisco_stig_reg

    - name: Force all notified handlers to run at this point, not waiting for normal sync points
      ansible.builtin.meta: flush_handlers
      check_mode: false

    - name: Debug
      ansible.builtin.debug:
        var: change_fact
      check_mode: false

    - name: List running jobs for the network_STIG_change.yml playbook
      when: change_fact == true
      ansible.controller.job_list:
        status: running
        # query: {"playbook": "network_STIG_change.yml"}
      register: STIG_job
      ignore_errors: true
      run_once: true
      delegate_to: localhost

    - name: Get the job from the list of running jobs
      when: STIG_job
      ansible.builtin.set_fact:
        job_url: "{{ STIG_job.invocation }}/#/jobs/playbook/{{ STIG_job.results[0].id }}/output"


    - name: Create Change Request
      when: change_fact == true
      servicenow.itsm.change_request:
        instance:
          host: "{{ SN_HOST }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
        state: new
        type: normal
        # service: "Network Routing"
        requested_by: "splunk_ansible_workflow"
        description: >
          "{{ inventory_hostname }} device is our of compliance
          URL for the Job: {{ job_url }}"
        short_description: "{{ inventory_hostname }}"
        priority: low
        impact: low
        risk: low
        category: network
        other:
          planned_start: "{{ lookup('pipe','date +%Y%m%d%H%M%S')}}"
          answer: true
      register: change_out
      check_mode: false
      delegate_to: localhost

    - name: Set fact for change number
      ansible.builtin.set_fact:
        #change_number: 'CHG0030022'
        change_number: "{{ change_out.record.number }}"

    - name: Debug change number
      debug:
        msg: "{{ change_number }}"

    # - name: Set change Number
    #   ansible.builtin.set_stats:
    #     data:
    #       change_number: "{{ change_number }}"


