- name: Cisco IOS XE STIG
  hosts: cisco,juniper
  gather_facts: false
  vars:
    change_fact: true
  tasks:

    # - name: Run Cisco STIG
    #   when: ansible_network_os == 'ios'
    #   vars:
    #     ignore_all_errors: False
    #   ansible.builtin.include_role:
    #     name: iosxeSTIG
    #   # notify: cisco_stig
    #   register: cisco_stig_reg

    # - name: Force all notified handlers to run at this point, not waiting for normal sync points
    #   ansible.builtin.meta: flush_handlers

    # - name: Debug
    #   ansible.builtin.debug:
    #     var: change_fact


    - name: Create incident
      when: change_fact == true
      servicenow.itsm.change_request:
        instance:
          host: "{{ SN_HOST }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
        state: new
        type: normal
        # service: "Network Routing"
        requested_by: "splunk_ansible_workflow"
        description: "{{ inventory_hostname }} device is out of compliance and needs to be brought into compliance"
        short_description: "{{ inventory_hostname }}"
        priority: low
        impact: low
        risk: low
        category: network
        other:
          planned_start: "{{ lookup('pipe','date +%Y%m%d%H%M%S')}}"
          answer: true
      register: change_out
      # register: snow_var
      delegate_to: localhost

    - name: Set fact for change number
      ansible.builtin.set_fact:
        #change_number: 'CHG0030022'
        change_number: "{{ change_out.record.number }}"

    - name: Debug change number
      debug:
        msg: "{{ change_number }}"

    # - name: Set change Number
    #   ansible.builtin.set_stats:
    #     data:
    #       change_number: "{{ change_number }}"


