- name: Cisco IOS XE STIG
  hosts: "{{ _hosts }}"
  gather_facts: false

  tasks:

    - name: List running jobs for the network_STIG_change.yml playbook
      ansible.controller.job_list:
        status: running
        query: {"name": "Network STIG Run"}
      run_once: true
      delegate_to: localhost
      check_mode: false
      register: STIG_job

    - name: Run Cisco STIG
      when: ansible_network_os == 'ios'
      ignore_errors: true
      vars:
        ignore_all_errors: False
      ansible.builtin.import_role:
        name: iosxeSTIG