- name: Get Network Devices
  hosts: ise_servers
# Read in some variables
  vars_files:
    - credentials.yaml  # read the ISE host and admin credentials
    
  gather_facts: false

  tasks:
    - name: Get user info for our network device IDs  # run through our list of groups and obtain the group information
      cisco.ise.network_device_info:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "{{ ise_verify }}"
      register: result

    - name: Print the result for each device ID
      ansible.builtin.debug:
        msg: 
        - "CSR1000v: {{ result.ise_response | selectattr('name', 'match', 'CSR1000v') | map(attribute='id') }}" 
        - "Cat8000: {{ result.ise_response | selectattr('name', 'match', 'Cat8000') | map(attribute='id') }}" 
     
    - name: Get user info for our network devices  # run through our list of groups and obtain the group information
      cisco.ise.network_device_info:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "{{ ise_verify }}"
        id: "{{ item }}"
      register: result_id
      loop: "{{ result.ise_response | map(attribute='id') }}"
    
    - name: Print the result for each device ID
      ansible.builtin.debug:
        var: result_id

   