download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/ansible-scm-1.2.2.tar.gz
format_version: 1.0.0
name: scm
namespace: ansible
server: https://galaxy.ansible.com/api/
signatures: []
version: 1.2.2
version_url: /api/v3/plugin/ansible/content/published/collections/index/ansible/scm/versions/1.2.2/
