---
- name: Clone a Repo to EE
  shell:
    cmd: "git clone http://gitea:gitea@ansible-1:3000/gitea/network-demos-repo.git"
    chdir: /tmp/
  delegate_to: localhost

- name: Backup cisco ios configuration
  cisco.ios.ios_config:
    backup: true
    backup_options:
      dir_path: "{{ backup_root }}/{{ inventory_hostname }}"
      filename: "{{ inventory_hostname }}_running.conf"
  register: config_output

# This task removes the Current configuration... from the top of IOS routers show run
- name: Remove non config lines - regexp
  ansible.builtin.lineinfile:
    path: "{{ config_output.backup_path }}"
    line: "Building configuration..."
    state: absent
  delegate_to: localhost

- name: Publish the changes
  ansible.scm.git_publish:
    path: "/tmp/network-demos-repo"
    token: "{{ password }}"
    user:
      name: "{{ username }}"
      email: "{{ email }}"
  delegate_to: localhost