download_url: https://galaxy.ansible.com/download/cisco-nxos-5.1.0.tar.gz
format_version: 1.0.0
name: nxos
namespace: cisco
server: https://galaxy.ansible.com/api/
signatures: []
version: 5.1.0
version_url: https://galaxy.ansible.com/api/v2/collections/cisco/nxos/versions/5.1.0/
