---
- name: DEPLOY CONTRACTS CONFIG

  #ignore_errors: true
  block:
    - name: Contract Filters
      cisco.aci.aci_filter:
        annotation: "{{ filter_item['vzFilter']['attributes']['annotation'] | default(omit, True) }}"
        tenant: "{{ filter_item['vzFilter']['attributes']['dn'] | split ('/flt-') | first | trim | split ('uni/tn-') | last | trim }}" 
        filter: "{{ filter_item['vzFilter']['attributes']['name'] | default(omit, True) }}"
        description: "{{ filter_item['vzFilter']['attributes']['desc'] | default(omit, True) }}"
      retries: 2
      async: 60
      poll: 0
      loop: "{{ filters }}"
      loop_control:
        loop_var: filter_item
        label: "{{ filter_item['vzFilter']['attributes']['dn'] | split ('/flt-') | first | trim | split ('uni/tn-') | last | trim }}-{{ filter_item['vzFilter']['attributes']['name'] | default(omit, True) }}"

    - name: Filter Entries
      cisco.aci.aci_filter_entry:
        annotation: "{{ entry_item['vzEntry']['attributes']['annotation'] | default(omit, True) }}"
        tenant: "{{ entry_item['vzEntry']['attributes']['dn'] | split ('/flt-') | first | trim | split ('uni/tn-') | last | trim }}" 
        filter: "{{ entry_item['vzEntry']['attributes']['dn'] | split ('/e-') | first | trim | split ('flt-') | last | trim }}" 
        entry: "{{ entry_item['vzEntry']['attributes']['name'] | default(omit, True) }}"
        ether_type: "{{ entry_item['vzEntry']['attributes']['etherT'] | default(omit, True) }}"
        ip_protocol: "{{ entry_item['vzEntry']['attributes']['prot'] | default(omit, True) }}"
        dst_port_start: "{{ entry_item['vzEntry']['attributes'][' dFromPort'] | default(omit, True) }}"
        dst_port_end: "{{ entry_item['vzEntry']['attributes'][' dToPort'] | default(omit, True) }}"
        src_port_start: "{{ entry_item['vzEntry']['attributes'][' sFromPort'] | default(omit, True) }}"
        src_port_end: "{{ entry_item['vzEntry']['attributes'][' sToPort'] | default(omit, True) }}"
      retries: 2
      async: 60
      poll: 0
      loop: "{{ entries }}"
      loop_control:
        loop_var: entry_item
        label: "{{ entry_item['vzEntry']['attributes']['dn'] | split ('/flt-') | first | trim | split ('uni/tn-') | last | trim }}-{{ entry_item['vzEntry']['attributes']['dn'] | split ('/e-') | first | trim | split ('flt-') | last | trim }}-{{ entry_item['vzEntry']['attributes']['name'] | default(omit, True) }}"

    - name: Tenant Contracts
      cisco.aci.aci_contract:
        annotation: "{{ contract_item['vzBrCP']['attributes']['annotation'] | default(omit, True) }}"
        contract: "{{ contract_item['vzBrCP']['attributes']['name'] | default(omit, True) }}"
        tenant: "{{ contract_item['vzBrCP']['attributes']['dn'] | split ('/brc-') | first | trim | split ('uni/tn-') | last | trim }}" 
        scope: "{{ contract_item['vzBrCP']['atributes']['scope'] | default(omit, True) }}"
        description: "{{ contract_item['vzBrCP']['atributes']['descr'] | default(omit, True) }}"
        timeout: 60
      retries: 2
      delay: 10
      async: 60
      poll: 0  
      loop: "{{ contracts }}"
      loop_control:
        loop_var: contract_item
        label: "{{ contract_item['vzBrCP']['attributes']['dn'] | split ('/brc-') | first | trim | split ('uni/tn-') | last | trim }}-{{ contract_item['vzBrCP']['attributes']['name'] | default(omit, True) }}"

    - name: Contract Subjects
      cisco.aci.aci_contract_subject:
        tenant: "{{ subj_item['vzSubj']['attributes']['dn'] | split ('/brc-') | first | trim | split ('uni/tn-') | last | trim }}" 
        contract: "{{ subj_item['vzSubj']['attributes']['dn'] | split ('/subj-') | first | trim | split ('brc-') | last | trim }}" 
        annotation: "{{ subj_item['vzSubj']['atributes']['annotation'] | default(omit, True) }}"
        subject: "{{ subj_item['vzSubj']['attributes']['name'] | default(omit, True) }}"
        timeout: 60
      retries: 2
      delay: 10
      async: 60
      poll: 0  
      loop: "{{ subjects }}"
      loop_control:
        loop_var: subj_item
        label: "{{ subj_item['vzSubj']['attributes']['dn'] | split ('/brc-') | first | trim | split ('uni/tn-') | last | trim }}-{{ subj_item['vzSubj']['attributes']['dn'] | split ('/subj-') | first | trim | split ('brc-') | last | trim }}-{{ subj_item['vzSubj']['attributes']['name'] | default(omit, True) }}"

    - name: Contracts Subjects Associated with Filters WITH FILTERS
      cisco.aci.aci_contract_subject_to_filter:
        tenant: "{{ filt_item['vzRsSubjFiltAtt']['attributes']['dn'] | split ('/brc-') | first | trim | split ('uni/tn-') | last | trim }}" 
        contract: "{{ filt_item['vzRsSubjFiltAtt']['attributes']['dn'] | split ('/subj-') | first | trim | split ('brc-') | last | trim }}" 
        subject: "{{ filt_item['vzRsSubjFiltAtt']['attributes']['dn'] | split ('/rss') | first | trim | split ('subj-') | last | trim }}" 
        filter: "{{ filt_item['vzRsSubjFiltAtt']['attributes']['tnVzFilterName'] | default(omit, True) }}" 
        timeout: 60     
      retries: 5
      delay: 10
      async: 60
      poll: 0 
      loop: "{{ associated }}"
      loop_control:
        loop_var: filt_item
        label: "{{ filt_item['vzRsSubjFiltAtt']['attributes']['dn'] | split ('/brc-') | first | trim | split ('uni/tn-') | last | trim }}-{{ filt_item['vzRsSubjFiltAtt']['attributes']['tnVzFilterName'] | default(omit, True) }}" 
    
    - name: Contract to EPG Binding Providers
      cisco.aci.aci_epg_to_contract:
        tenant: "{{ provider_item['fvRsProv']['attributes']['dn'] | split ('/ap-') | first | trim | split ('uni/tn-') | last | trim }}" 
        ap: "{{ provider_item['fvRsProv']['attributes']['dn'] | split ('/epg-') | first | trim | split ('ap-') | last | trim }}" 
        epg: "{{ provider_item['fvRsProv']['attributes']['dn'] | split ('/rsp') | first | trim | split ('epg-') | last | trim }}" 
        contract: "{{ provider_item['fvRsProv']['attributes']['tnVzBrCPName'] | default(omit, True) }}" 
        contract_type: provider
        timeout: 60     
      retries: 5
      delay: 10
      async: 60
      poll: 0  
      loop: "{{ provider }}"
      loop_control:
        loop_var: provider_item
        label: "{{ provider_item['fvRsProv']['attributes']['dn'] | split ('/ap-') | first | trim | split ('uni/tn-') | last | trim }}-{{ provider_item['fvRsProv']['attributes']['tnVzBrCPName'] | default(omit, True) }}" 

    - name: Contract to EPG Binding Consumers
      cisco.aci.aci_epg_to_contract:
        tenant: "{{ consumer_item['fvRsCons']['attributes']['dn'] | split ('/ap-') | first | trim | split ('uni/tn-') | last | trim }}" 
        ap: "{{ consumer_item['fvRsCons']['attributes']['dn'] | split ('/epg-') | first | trim | split ('ap-') | last | trim }}" 
        epg: "{{ consumer_item['fvRsCons']['attributes']['dn'] | split ('/rsc') | first | trim | split ('epg-') | last | trim }}" 
        contract: "{{ consumer_item['fvRsCons']['attributes']['tnVzBrCPName'] | default(omit, True)  }}" 
        contract_type: consumer
        timeout: 60     
      retries: 5
      delay: 10
      async: 60
      poll: 0  
      loop: "{{ consumer }}"
      loop_control:
        loop_var: consumer_item
        label: "{{ consumer_item['fvRsCons']['attributes']['dn'] | split ('/ap-') | first | trim | split ('uni/tn-') | last | trim }}-{{ consumer_item['fvRsCons']['attributes']['tnVzBrCPName'] | default(omit, True) }}" 