---
- name: Clone a Repo to EE
  shell:
    cmd: "git clone http://gitea:gitea@ansible-1:3000/gitea/network-demos-repo.git"
    chdir: /tmp/
  delegate_to: localhost

- name: Diff against Device Running Config and Netbox Intended Config
  cisco.ios.config:
    intended_config: "{{ lookup('file', '{{ intended_conf_dir }}/{{ inventory_hostname }}_intended.conf') }}"
    diff_against: intended
    diff_ignore_lines:
     - 'revocation-check crl'
     - 'quit'
 


