---
- name: FABRIC ACCESS POLICIES

  vars:
    aci_login: &aci_login
      hostname: "{{ apic_host }}"
      username: "{{ apic_username }}"
      password: "{{ apic_password }}"
      validate_certs: "{{ apic_validate_certs }}"
      ignore: true

  delegate_to: localhost

  block:
    - name: Read CSV File csv_files/aci_fabric_access_sw_profile_selector.csv
      community.general.read_csv:
        path: ../csv_files/day0/aci_fabric_access_sw_profile_selector.csv # location of CSV file
      register: sw_profile_selector

    - name: Create Switch Policy Profiles
      cisco.aci.aci_switch_policy_leaf_profile:
        <<: *aci_login
        leaf_profile: "{{sw_pol_item.sw_policy_profile | default(omit, True) }}"
      retries: 2
      delay: 5
      loop: "{{ sw_profile_selector.list }}"
      loop_control:
        loop_var: sw_pol_item
        label: "{{sw_pol_item.sw_policy_profile}}"
      ignore_errors: "{{ ignore }}"

    - name: ASSOCIATING AN INTERFACE SELECTOR PROFILE TO A SWITCH POLICY LEAF PROFILE
      cisco.aci.aci_interface_selector_to_switch_policy_leaf_profile:
        <<: *aci_login
        leaf_profile: "{{ sw_pol_selector_item.sw_policy_profile | default(omit, True) }}"
        interface_selector: "{{ sw_pol_selector_item.interface_selector_profile | default(omit, True) }}"
      retries: 2
      delay: 5
      loop: "{{ sw_profile_selector.list }}"
      loop_control:
        loop_var: sw_pol_selector_item
        label: "{{ sw_pol_selector_item.interface_selector_profile }}"
      ignore_errors: "{{ ignore }}"

    - name: Read CSV File csv_files/aci_fabric_access_policies.csv
      community.general.read_csv:
        path: ../csv_files/day0/aci_fabric_access_policies.csv # location of CSV file
      register: aci_fabric_access

    - name: Create CDP Interface Policy to enable/disable CDP
      cisco.aci.aci_interface_policy_cdp:
        <<: *aci_login
        name: "{{  cdp_item.cdp_policy | default(omit, True) }}"
        admin_state: "{{ cdp_item.cdp_enabled | default(omit, True) }}"
      retries: 2
      delay: 5
      loop: "{{ aci_fabric_access.list }}"
      loop_control:
        loop_var: cdp_item
        label: "{{  cdp_item.cdp_policy }}"
      ignore_errors: "{{ ignore }}"

    - name: Create MCP Interface Policy to enable/disable MCP
      cisco.aci.aci_interface_policy_mcp:
        <<: *aci_login
        mcp: "{{  mcp_item.mcp_policy | default(omit, True) }}"
        admin_state: "{{ mcp_item.mcp_enabled | default(omit, True) }}"
      retries: 2
      delay: 5
      loop: "{{ aci_fabric_access.list }}"
      loop_control:
        loop_var: mcp_item
        label: "{{  mcp_item.mcp_policy }}"
      ignore_errors: "{{ ignore }}"
         

    - name: Create LLDP Interface Policy to enable/disable LLDP
      cisco.aci.aci_interface_policy_lldp:
        <<: *aci_login
        name: "{{  lldp_item.lldp_policy | default(omit, True) }}"
      retries: 2
      delay: 5
      loop: "{{ aci_fabric_access.list }}"
      loop_control:
        loop_var: lldp_item
        label: "{{  lldp_item.lldp_policy }}"
      ignore_errors: "{{ ignore }}"

    - name: Create a Link Level Policy
      cisco.aci.aci_interface_policy_link_level:
        <<: *aci_login
        link_level_policy: "{{  level_item.link_level_policy | default(omit, True) }}"
        description: via Ansible
        auto_negotiation: on
        speed: 10G
        link_debounce_interval: 100
        forwarding_error_correction: cl91-rs-fec
      retries: 2
      delay: 5
      loop: "{{ aci_fabric_access.list }}"
      loop_control:
        loop_var: level_item
        label: "{{  level_item.link_level_policy }}"
      ignore_errors: "{{ ignore }}"

    - name: Add Interface Polices to leaf policy group
      cisco.aci.aci_interface_policy_leaf_policy_group:
        <<: *aci_login
        policy_group: "{{  add_ifselector_item.policy_group | default(omit, True)  }}"
        description: "{{  add_ifselector_item.pg_descr | default(omit, True)  }}"
        lag_type: "{{  add_ifselector_item.lag_type | default(omit, True)  }}"
        link_level_policy: "{{  add_ifselector_item.link_level_policy }}"
        cdp_policy: "{{  add_ifselector_item.cdp_policy | default(omit, True) }}"
        mcp_policy: "{{  add_ifselector_item.mcp_policy | default(omit, True) }}"
        lldp_policy: "{{  add_ifselector_item.lldp_policy | default(omit, True) }}"
        # stp_interface_policy: "{{  add_ifselector_item.stp_interface_policy }}"
        # egress_data_plane_policing_policy: "{{  add_ifselector_item.egress_data_plane_policing_policy }}"
        # ingress_data_plane_policing_policy: "{{  add_ifselector_item.ingress_data_plane_policing_policy }}"
        # priority_flow_control_policy: "{{  add_ifselector_item.priority_flow_control_policy }}"
        # fibre_channel_interface_policy: "{{  add_ifselector_item.fibre_channel_interface_policy }}"
        # slow_drain_policy: "{{  add_ifselector_item.slow_drain_policy }}"
        port_channel_policy: "{{  add_ifselector_item.port_channel_policy | default(omit, True) }}"
        # monitoring_policy: "{{  add_ifselector_item.monitoring_policy }}"
        # storm_control_interface_policy: "{{  add_ifselector_item.storm_control_interface_policy }}"
        # l2_interface_policy: "{{  add_ifselector_item.l2_interface_policy }}"
        # port_security_policy: "{{  add_ifselector_item.port_security_policy }}"
        aep: "{{  add_ifselector_item.aep | default(omit, True)  }}"
      retries: 2
      delay: 5
      ignore_errors: "{{ ignore }}"
      loop: "{{ aci_fabric_access.list }}"
      loop_control:
        loop_var: add_ifselector_item
