changed: false
static_bindings:
-   fvRsPathAtt:
        attributes:
            annotation: orchestrator:ansible
            childAction: ''
            descr: ''
            dn: uni/tn-Ansible/ap-Ansible_AP/epg-web/rspathAtt-[topology/pod-1/protpaths-101-102/pathep-[Ansible_FI-1A]]
            encap: vlan-300
            extMngdBy: ''
            forceResolve: 'yes'
            instrImedcy: immediate
            lcC: ''
            lcOwn: local
            modTs: '2024-06-23T18:07:23.476+00:00'
            mode: regular
            monPolDn: uni/tn-common/monepg-default
            primaryEncap: unknown
            rType: mo
            state: unformed
            stateQual: none
            status: ''
            tCl: fabricPathEp
            tDn: topology/pod-1/protpaths-101-102/pathep-[Ansible_FI-1A]
            tType: mo
            uid: '15374'
            userdom: ':all:'
-   fvRsPathAtt:
        attributes:
            annotation: orchestrator:ansible
            childAction: ''
            descr: ''
            dn: uni/tn-Ansible/ap-Ansible_AP/epg-web/rspathAtt-[topology/pod-1/protpaths-101-102/pathep-[Ansible_FI-1B]]
            encap: vlan-300
            extMngdBy: ''
            forceResolve: 'yes'
            instrImedcy: immediate
            lcC: ''
            lcOwn: local
            modTs: '2024-06-23T18:07:25.420+00:00'
            mode: regular
            monPolDn: uni/tn-common/monepg-default
            primaryEncap: unknown
            rType: mo
            state: unformed
            stateQual: none
            status: ''
            tCl: fabricPathEp
            tDn: topology/pod-1/protpaths-101-102/pathep-[Ansible_FI-1B]
            tType: mo
            uid: '15374'
            userdom: ':all:'
-   fvRsPathAtt:
        attributes:
            annotation: orchestrator:ansible
            childAction: ''
            descr: ''
            dn: uni/tn-Ansible/ap-Ansible_AP/epg-db/rspathAtt-[topology/pod-1/protpaths-101-102/pathep-[Ansible_FI-1A]]
            encap: vlan-301
            extMngdBy: ''
            forceResolve: 'yes'
            instrImedcy: immediate
            lcC: ''
            lcOwn: local
            modTs: '2024-06-23T18:07:27.372+00:00'
            mode: regular
            monPolDn: uni/tn-common/monepg-default
            primaryEncap: unknown
            rType: mo
            state: unformed
            stateQual: none
            status: ''
            tCl: fabricPathEp
            tDn: topology/pod-1/protpaths-101-102/pathep-[Ansible_FI-1A]
            tType: mo
            uid: '15374'
            userdom: ':all:'
-   fvRsPathAtt:
        attributes:
            annotation: orchestrator:ansible
            childAction: ''
            descr: ''
            dn: uni/tn-Ansible/ap-Ansible_AP/epg-db/rspathAtt-[topology/pod-1/protpaths-101-102/pathep-[Ansible_FI-1B]]
            encap: vlan-301
            extMngdBy: ''
            forceResolve: 'yes'
            instrImedcy: immediate
            lcC: ''
            lcOwn: local
            modTs: '2024-06-23T18:07:29.300+00:00'
            mode: regular
            monPolDn: uni/tn-common/monepg-default
            primaryEncap: unknown
            rType: mo
            state: unformed
            stateQual: none
            status: ''
            tCl: fabricPathEp
            tDn: topology/pod-1/protpaths-101-102/pathep-[Ansible_FI-1B]
            tType: mo
            uid: '15374'
            userdom: ':all:'
failed: false
