changed: false
tenants:
-   fvTenant:
        attributes:
            annotation: ''
            childAction: ''
            descr: ''
            dn: uni/tn-infra
            extMngdBy: ''
            lcOwn: local
            modTs: '2020-11-08T20:47:58.622+00:00'
            monPolDn: uni/tn-common/monepg-default
            name: infra
            nameAlias: ''
            ownerKey: ''
            ownerTag: ''
            status: ''
            uid: '0'
            userdom: all
-   fvTenant:
        attributes:
            annotation: ''
            childAction: ''
            descr: ''
            dn: uni/tn-mgmt
            extMngdBy: ''
            lcOwn: local
            modTs: '2020-11-08T20:47:59.072+00:00'
            monPolDn: uni/tn-common/monepg-default
            name: mgmt
            nameAlias: ''
            ownerKey: ''
            ownerTag: ''
            status: ''
            uid: '0'
            userdom: all
-   fvTenant:
        attributes:
            annotation: ''
            childAction: ''
            descr: ''
            dn: uni/tn-common
            extMngdBy: ''
            lcOwn: local
            modTs: '2020-11-08T20:47:58.897+00:00'
            monPolDn: uni/tn-common/monepg-default
            name: common
            nameAlias: ''
            ownerKey: ''
            ownerTag: ''
            status: ''
            uid: '0'
            userdom: all
-   fvTenant:
        attributes:
            annotation: ''
            childAction: ''
            descr: ''
            dn: uni/tn-Heroes
            extMngdBy: ''
            lcOwn: local
            modTs: '2020-11-08T20:47:59.098+00:00'
            monPolDn: uni/tn-common/monepg-default
            name: Heroes
            nameAlias: ''
            ownerKey: ''
            ownerTag: ''
            status: ''
            uid: '15374'
            userdom: ':all:'
-   fvTenant:
        attributes:
            annotation: ''
            childAction: ''
            descr: ''
            dn: uni/tn-SnV
            extMngdBy: ''
            lcOwn: local
            modTs: '2020-11-08T20:47:59.010+00:00'
            monPolDn: uni/tn-common/monepg-default
            name: SnV
            nameAlias: ''
            ownerKey: ''
            ownerTag: ''
            status: ''
            uid: '15374'
            userdom: ':all:'
failed: false
