---
- name: VALIDATE THE TENANT HEALTH SCORE

  # We prepare an aci_login anchor for convenience
  vars:
    aci_login: &aci_login
      hostname: "{{ apic_host }}"
      username: "{{ apic_username }}"
      password: "{{ apic_password }}"
      validate_certs: "{{ apic_validate_certs }}"

  # We define the delegate_to at the block-level
  delegate_to: localhost

  block:
    - name: Read CSV File
      read_csv:
        path: ../csv_files/day1/aci_static_binding.csv # location of CSV file
      register: aci_static_binding_to_epg

    - name: Get Tenant Health Score
      aci_rest:
        <<: *aci_login
        path: /api/node/mo/uni/tn-{{aci_static_binding_to_epg.list[0].tenant}}/health.json?query-target=self
        method: get
      register: health

    - name: Set_fact
      set_fact:
        health_score: "{{health.imdata[0].healthInst.attributes.cur}}"

    #- name: Validate Tenant Health

    - name: Assert The Tenant Health Score is equal or greater than (94)
      assert:
        that: health_score | int >= 94
        fail_msg: "Failure! The The Tenant Health Score is {{health_score}} Please review faults"
        success_msg: "Success! The Tenant Health Score is {{health_score}}"
