---
apic:
  hosts:
    apic1:
      #apic_host: 10.10.20.14 # change for devnet reservered sandbox
      apic_host: sandboxapicdc.cisco.com #change for always on sandbox
      #apic_host: 192.168.0.180
devbox:
  hosts:
    10.10.20.50
