---
- name: ACI Brownfield to YAML Collection
  hosts: apic
  gather_facts: no

  tasks:
  - name: Retrieve a repository from a distant location and make it available to the local EE
    ansible.scm.git_retrieve:
      origin:
        url: "http://gitea:gitea@ansible-1:3000/gitea/network-demos-repo.git"
      parent_directory: /tmp
      branch:
          name: master
          duplicate_detection: no  
    run_once: true
    register: repository
    delegate_to: localhost

  - name: load system role
    include_role:
       name: "{{ item }}"
    loop: 
        - "../roles/day0_snapshot"
        - "../roles/brownfield_fabric_access_collect"
        - "../roles/brownfield_l3out_collect" 
        - "../roles/brownfield_contracts_collect"
        - "../roles/brownfield_tenant_collect" 
        
  - name: Publish the changes
    ansible.scm.git_publish:
      path: "{{ repository['path'] }}"
      token: "{{ password }}"
      user:
        name: "{{ username }}"
        email: "{{ email }}"
    delegate_to: localhost
    run_once: true
        


    