---
- name: Day0-1 deployment
  hosts: apic
  connection: local
  gather_facts: no

  tasks:
  - name: load system role
    include_role:
       name: "{{ item }}"
    loop: 
        - "../roles/brownfield_tenant_collect"
        


    