---
- name: ROLLBACK TO ORIGINAL BASELINE CONFIG
  hosts: apic
  gather_facts:
    no

    # We prepare an aci_login anchor for convenience
  vars:
    aci_login: &aci_login
      hostname: "{{ apic_host }}"
      username: "{{ apic_username }}"
      password: "{{ apic_password }}"
      validate_certs: "{{ apic_validate_certs }}"

  tasks:
    - name: Read Snapshot
      cisco.aci.aci_config_snapshot:
        <<: *aci_login
        state: query
      register: snap
      delegate_to: localhost

    - name: print to baseline Snapshot
      debug:
        var: snap.current[0].configSnapshot.attributes.name

    - name: Rollback Configuration
      cisco.aci.aci_config_rollback:
        <<: *aci_login
        snapshot: "{{ snap.current[0].configSnapshot.attributes.name }}"
        import_policy: rollback_config
        export_policy: config_backup
        state: rollback
        description: "Rollback initial config"
        import_mode: atomic
        import_type: replace
        fail_on_decrypt: yes
      delegate_to: localhost
