---
- name: Brownfield Deployment (new configs)
  hosts: apic
  gather_facts: no

  tasks:
  - name: load system role
    include_role:
       name: "{{ item }}"
    loop: 
      - "../roles/brownfield_fabric_access_deploy"
      - "../roles/brownfield_tenant_deploy" 
      - "../roles/brownfield_contracts_deploy"
      - "../roles/brownfield_l3out_deploy" 

  - name: Retrieve a repository from a distant location and make it available to the local EE
    ansible.scm.git_retrieve:
      origin:
        url: "http://gitea:gitea@ansible-1:3000/gitea/network-demos-repo.git"
      parent_directory: /tmp
      branch:
          name: master
          duplicate_detection: no  
    run_once: true
    register: repository
    delegate_to: localhost

  - name: Disable New Configs by Renaming
    ansible.builtin.copy: 
      src: "{{ item.src }}" 
      dest: "{{ item.dest }}"
    loop:
      - src: "{{ repository['path'] }}/cisco_aci/roles/brownfield_fabric_access_deploy/vars/main/"
        dest: "{{ repository['path'] }}/cisco_aci/roles/brownfield_fabric_access_deploy/old/main/"
      - src: "{{ repository['path'] }}/cisco_aci/roles/brownfield_tenant_deploy/vars/main/"
        dest: "{{ repository['path'] }}/cisco_aci/roles/brownfield_tenant_deploy/old/main/"     
      - src: "{{ repository['path'] }}/cisco_aci/roles/brownfield_contracts_deploy/vars/main/"
        dest: "{{ repository['path'] }}/cisco_aci/roles/brownfield_contracts_deploy/old/main/"
      - src: "{{ repository['path'] }}/cisco_aci/roles/brownfield_l3out_deploy/vars/main/"
        dest: "{{ repository['path'] }}/cisco_aci/roles/brownfield_l3out_deploy/old/main/"
    delegate_to: localhost
    ignore_errors: true
  
  - name: Delete Vars dir
    ansible.builtin.file: 
      path: "{{ item.src }}" 
      state: absent
    loop:
      - src: "{{ repository['path'] }}/cisco_aci/roles/brownfield_fabric_access_deploy/vars"
      - src: "{{ repository['path'] }}/cisco_aci/roles/brownfield_tenant_deploy/vars"   
      - src: "{{ repository['path'] }}/cisco_aci/roles/brownfield_contracts_deploy/vars"
      - src: "{{ repository['path'] }}/cisco_aci/roles/brownfield_l3out_deploy/vars"

  - name: Publish the changes
    ansible.scm.git_publish:
      path: "{{ repository['path'] }}"
      token: "{{ password }}"
      user:
        name: "{{ username }}"
        email: "{{ email }}"
    delegate_to: localhost
    run_once: true  

        


    