---
backup_root: "/tmp/network-demos-repo/netbox/backups/{{ inventory_hostname }}"
intended_conf_dir: "/tmp/network-demos-repo/netbox/intended_configs/{{ inventory_hostname }}"
exclusion_pattern: "(^! Command:)|(^! device:)"