---
- name: Gather configuration information from network devices
  hosts: catalyst
  gather_facts: false

  tasks:

    - name: Retrieve a repository from a distant location and make it available to the local EE
      ansible.scm.git_retrieve:
        origin:
          url: "add your repo url"
        parent_directory: /tmp/
        branch:
            name: "main"
            duplicate_detection: no  
      delegate_to: "localhost"
      run_once: true

    - name: Gather network information
      cisco.ios.ios_facts:
        gather_network_resources:
          - 'all'
          #- "acl_interfaces"
          #- "acls"
          #- "bgp_address_family"
          #- "bgp_global"
          #- "hostname"
          #- "interfaces"
          #- "l2_interfaces"
          #- "l3_interfaces"
          #- "lacp"
          #- "lacp_interfaces"
          #- "lag_interfaces"
          #- "lldp_global"
          #- "lldp_interfaces"
          #- "logging_global"
          #- "ntp_global"
          #- "ospf_interfaces"
          #- "ospfv2"
          #- "ospfv3"
          #- "prefix_lists"
          #- "route_maps"
          #- "service"
          #- "snmp_server"
          #- "static_routes"
          #- system module 
          #- user 
          #- vlans 
          #- vrf module 

    - name: Create a host_vars directory if it does not exist
      ansible.builtin.file:
        path: "host_vars/"
        state: directory
        mode: '0755'

    - name: Add network facts to the host_vars
      ansible.builtin.copy:
        content: "{{ ansible_network_resources | to_nice_yaml }}"
        dest: "host_vars/{{ inventory_hostname }}/brownfield.yaml"

    - name: Publish the changes
      ansible.scm.git_publish:
        path: "{{ repository['path'] }}"
        token: "{{ password }}"
        user:
          name: "{{ username }}"
          email: "{{ email }}"
      when: inventory_hostname == 'localhost'