---
- name: Backup Cisco Configs to Gitea in Branches
  hosts:
    - localhost
    - routers
  gather_facts: False
 
  tasks:
    - name: Retrieve a repository from a distant location and make it available to the local EE
      ansible.scm.git_retrieve:
        origin:
          url: "http://gitea:gitea@ansible-1:3000/gitea/network-demos-repo.git"
        parent_directory: /tmp/
      register: repository
      when: inventory_hostname == 'localhost'

    - name: Network Backup and Resource Manager
      ansible.builtin.include_role:
        name: network.backup.run
      vars:
        operation: backup
        type: full
        data_store:
          local: "/tmp/network-backup-repo/network_backup_files/"
      when: inventory_hostname != 'localhost'

    - name: Publish the changes
      ansible.scm.git_publish:
        path: "{{ repository['path'] }}"
        token: "{{ token }}"
        user:
          name: "{{ username }}"
          email: "{{ email }}"
      when: inventory_hostname == 'localhost'