---
- name: Check Diif from Intended Config in  Gitea in Branches
  hosts:
    - localhost
    - cisco
    - arista
    - juniper
  gather_facts: False

  tasks:
    - name: Retrieve a repository from a distant location and make it available to the local EE
      ansible.scm.git_retrieve:
        origin:
          url: "http://gitea:gitea@ansible-1:3000/gitea/network-demos-repo.git"
        parent_directory: /tmp/
      register: repository
      when: inventory_hostname == 'localhost'

    - name: Network Backup and Resource Manager
      ansible.builtin.include_role:
        name: network.backup.run
      vars:
        ansible_connection: network_cli
        operation: diff
        type: full
        data_store:
          local: "/tmp/network-demos-repo/network_backup_files"
      when: inventory_hostname != 'localhost'

    