---
- name: Check Diif from Intended Config in  Gitea in Branches
  hosts:
    - localhost
    - cisco
    - arista
    - juniper
  gather_facts: False

  tasks:
    - name: Clone a Repo to EE
      ansible.builtin.shell:
        cmd: "git clone -b {{ scm_branch }} http://gitea:gitea@ansible-1:3000/gitea/network-demos-repo.git"
        chdir: /tmp/
      delegate_to: "localhost"
      run_once: true

    - name: Network Backup and Resource Manager
      ansible.builtin.include_role:
        name: network.backup.run
      vars:
        ansible_connection: network_cli
        operation: diff
        type: full
        data_store:
          local: "/tmp/network-demos-repo/network_backup_files"
      when: inventory_hostname != 'localhost'

    