---
- name: Restore Configs from Gitea in Branches to Cisco
  hosts: "{{ _group }}"
  gather_facts: False
  vars:
    ansible_network_cli_ssh_type: paramiko
    ansible_connection: network_cli
    ansible_network_os: cisco.ios.ios
    
  tasks:
    - name: Clone a Repo to EE
      ansible.builtin.shell:
        cmd: "git clone -b {{ scm_branch }} http://gitea:gitea@ansible-1:3000/gitea/network-demos-repo.git"
        chdir: /tmp/
      delegate_to: "localhost"
      run_once: true

    - name: enable scp
      cisco.ios.ios_config:
       lines: ip scp server enable
       save_when: always
      when: inventory_hostname in groups['cisco']
     
    - name: copy file to cisco
      ansible.netcommon.net_put:
        src: /tmp/network-demos-repo/network_backup_files/{{ inventory_hostname }}.txt
        dest: nvram:startup-config
      when: inventory_hostname in groups['cisco']
      register: cisco_changed

    - name: reload the os
      cisco.ios.ios_command:
        commands: 
          - command: reload
            prompt: 'Proceed with reload\? \[confirm\]'
            answer: 'y'
      when: 
      - inventory_hostname in groups['cisco']
      - cisco_changed.changed

    - name: waiting for reboot
      wait_for:
        host: "{{ ansible_host }}"
        port: 22
        delay: 60
        timeout: 350
      connection: network_cli
      delegate_to: localhost
      when: 
      - inventory_hostname in groups['cisco']
      - cisco_changed.changed
 
- name: Restore Configs from Gitea in Branches to Arista
  hosts: "{{ _group }}"
  gather_facts: False
  vars:
    ansible_network_cli_ssh_type: paramiko
     
  tasks:    

    - name: enable SCP
      arista.eos.eos_config:
        lines: 
        - username ec2-user privilege 15 role network-admin nopassword
        - aaa authentication login console local
        - aaa authorization exec default local
        save_when: always
      when: inventory_hostname in groups['arista']
  
    - name: copy file to arista
      ansible.netcommon.net_put:
        src: /tmp/network-demos-repo/network_backup_files/{{ inventory_hostname }}.txt
        dest: //mnt/flash/startup-config
      when: inventory_hostname in groups['arista']

    - name: reload the os
      ansible.netcommon.cli_command:
        command: reload
        check_all: true
        prompt: 
          - 'System configuration has been modified. Save\? \[yes/no/cancel/diff\]:'
          - 'Proceed with reload\? \[confirm\]'
        answer: 
          - 'n'
          - 'y'
      when: inventory_hostname in groups['arista']

    - name: waiting for reboot
      wait_for:
        host: "{{ ansible_host }}"
        port: 22
        delay: 60
        timeout: 350
      connection: network_cli
      delegate_to: localhost
      when: inventory_hostname in groups['arista']

- name: Restore Configs from Gitea in Branches to Juniper
  hosts: "{{ _group }}"
  gather_facts: False
  vars:
    #ansible_network_cli_ssh_type: paramiko
    #ansible_connection: network_cli
    #ansible_network_os: junipernetworks.junos.junos
     
  tasks:    
  
    #- name: copy file to juniper
    #  ansible.netcommon.net_put:
    #    src: /tmp/network-demos-repo/network_backup_files/{{ inventory_hostname }}.txt
    #    dest: /var/tmp/{{ inventory_hostname }}.txt
    #  when: inventory_hostname in groups['juniper']

    - name: push configs to devices
      junipernetworks.junos.junos_config:
        src: /tmp/network-demos-repo/network_backup_files/{{ inventory_hostname }}.txt
        confirm_commit: true
        update: override
      when: inventory_hostname in groups['juniper']



    