---
- name: Backup Cisco Configs to Gitea in Branches
  hosts: "{{ _group }}"
  gather_facts: True

  tasks:
    - name: Clone a Repo to EE
      ansible.builtin.shell:
        cmd: "git clone -b {{ scm_branch }} http://gitea:gitea@ansible-1:3000/gitea/network-demos-repo.git"
        chdir: /tmp/
      delegate_to: "localhost"
      run_once: true

    - debug:
        var: ansible_date_time
      delegate_to: "localhost"

    - name: The network restore task
      ansible.builtin.include_role:
        name: network.restore.run
      vars:
        operation: restore
        network_backup_path: "/tmp/network-demos-repo/network_backup_files/{{inventory_hostname}}.txt"