---
- name: Ping Endpoints
  hosts: cisco,juniper
  gather_facts: false

  vars:
   ping_dest: 
    - 8.8.8.8
   ansible_connection: network_cli
    
  tasks:
  - name: Test reachability to destinations
    ansible.netcommon.net_ping:
      dest: "{{ item }}"
    loop: "{{ ping_dest }}"