changed: false
consumer:
-   fvRsCons:
        attributes:
            accessPrivilege: USER
            annotation: orchestrator:ansible
            childAction: ''
            ctrctUpd: ctrct
            deplInfo: ''
            dn: uni/tn-Ansible/ap-Ansible_AP/epg-db/rscons-web
            extMngdBy: ''
            forceResolve: 'yes'
            intent: install
            lcOwn: local
            modTs: '2024-06-23T20:36:52.877+00:00'
            monPolDn: uni/tn-common/monepg-default
            prio: unspecified
            rType: mo
            state: formed
            stateQual: none
            status: ''
            tCl: vzBrCP
            tContextDn: ''
            tDn: uni/tn-Ansible/brc-web
            tRn: brc-web
            tType: name
            tnVzBrCPName: web
            triggerSt: triggerable
            uid: '15374'
            updateCollection: 'no'
            userdom: ':all:'
failed: false
