---
- name: READ TENANT CONFIG

  vars:
    aci_login: &aci_login
      hostname: "{{ apic_host }}"
      username: "{{ apic_username }}"
      password: "{{ apic_password }}"
      validate_certs: "{{ apic_validate_certs }}"

  delegate_to: localhost
  ignore_errors: true

  block:
    #- ansible.builtin.include_vars:
    #  file: apic1/tenants.yaml
   
    - name: Deploy Tenant
      cisco.aci.aci_tenant:
        <<: *aci_login
        state: present
        tenant: "{{ tenant_item['fvTenant']['attributes']['name'] | default(omit, True) }}"
        description: "{{ tenant_item['fvTenant']['attributes']['descr']| default(omit, True) }}"
      loop: "{{ current }}"
      loop_control:
        loop_var: tenant_item
    
     

    