- hosts: dnac_servers
  vars_files:
    - vars/credentials.yml
  gather_facts: no
  connection: local
  tasks:
       
    - name: Get all Network Device Chassis Details
      cisco.dnac.network_device_chassis_details_info:
        dnac_host: "{{dnac_host}}"
        dnac_username: "{{dnac_username}}"
        dnac_password: "{{dnac_password}}"
        dnac_verify: "{{dnac_verify}}"
        dnac_port: "{{dnac_port}}"
        dnac_version: "{{dnac_version}}"
        dnac_debug: "{{dnac_debug}}"
        deviceId: "{{ device_id }}"
      register: result

    - name: Current Device Info
      debug:
        msg: "{{ result }}"


    