- name: Prepare to Collect Configs from DNAC
  hosts: 
    - dnac_servers
    - sw1
    - sw2
    - sw3 
    - sw4
  gather_facts: false
  vars_files:
    - vars/credentials.yml
  connection: local
  tasks:
    - name: Get Devices
      include_tasks: 'compliance_assert.yml'
      loop: "{{ device_id }}"
      

