- hosts: dnac_servers
  vars_files:
    - vars/credentials.yml
  gather_facts: no
  connection: local
  tasks:
    - name: Get all Topology Network Health
      cisco.dnac.topology_network_health_info:
        dnac_host: "{{dnac_host}}"
        dnac_username: "{{dnac_username}}"
        dnac_password: "{{dnac_password}}"
        dnac_verify: "{{dnac_verify}}"
        dnac_port: "{{dnac_port}}"
        dnac_version: "{{dnac_version}}"
        dnac_debug: "{{dnac_debug}}"
        timestamp: "{{ time }}000"
      register: health

    - name: Topology Health
      debug:
        msg: "{{ health }}"
