- name: Rules with kafka as source
  hosts: localhost
  sources:
    - ansible.eda.kafka:
        topic: telegraf
        host: ip-172-16-213-105.us-east-2.compute.internal
        port: 9092
        group_id:
  rules:
    - name: Retrieve Data and Launch Job-template
      condition: events.body.fields.latest_return_code": "ret-code-timeout"
      action:
        debug:
          msg: Simple debug message
        
