- name: Playbook to configure ansible controller
  hosts: localhost
  connection: local
  vars:
    user: "{{ username }}"

  environment:
    CONTROLLER_HOST: "ansible-1"
    CONTROLLER_USERNAME: "admin"
    CONTROLLER_PASSWORD: "{{ password }}"
    CONTROLLER_VERIFY_SSL: false

  tasks:
    - name: Create projects
      ansible.controller.project:
        name: Student Project
        organization: "Red Hat network organization"
        scm_url: "http://ansible-1:3000/gitea/network-demos-repo.git"
        scm_type: git
        allow_override: true
        state: present
        scm_update_on_launch: yes

    - name: Add group
      ansible.controller.group:
        name: cisco
        variables:
          ansible_connection: network_cli
          ansible_network_os: cisco.ios.ios
        inventory: "Workshop Inventory"
        state: present

    - name: Add group
      ansible.controller.group:
        name: arista
        variables:
          ansible_connection: network_cli
          ansible_network_os: arista.eos.eos
          ansible_become: "true"
          ansible_become_method: enable
        inventory: "Workshop Inventory"

    - name: Add group
      ansible.controller.group:
        name: juniper
        variables:
          ansible_connection: netconf
          ansible_network_os: junipernetworks.junos.junos
        inventory: "Workshop Inventory"
        state: present

    - name: Create Execution Environments
      ansible.controller.execution_environment:
        name: "Validated Network"
        image: registry.gitlab.com/redhatautomation/validated-network-ee:latest
        pull: missing

    - name: Gitea Credential Type
      ansible.controller.credential_type:
        injectors:
          extra_vars:
            email: "{{ email | default ('{{ email }}') }}"
            password: "{{ git_password | default ('{{ git_password }}') }}"
            username: "{{ username | default ('{{ username }}') }}"
            token: "{{ git_password | default ('{{ git_password }}') }}"
        inputs:
          fields:
            - id: username
              label: Username
              type: string
            - id: password
              label: Password
              secret: true
              type: string
            - id: email
              label: Email
              type: string
          required:
            - username
            - password
            - email
        kind: cloud
        name: Gitea Student

    - name: Gitea Credential
      ansible.controller.credential:
        credential_type: Gitea Student
        description: ""
        inputs:
          username: "gitea"
          password: "gitea"
          email: admin@example.com
        name: Gitea Credential
        organization: "Red Hat network organization"


  # This Starts the Cisco Meraki Section
    - name: Meraki Credential Type
      ansible.controller.credential_type:
        injectors:
          extra_vars:
             meraki_key: "{{ MERAKI_KEY | default ('{{MERAKI_KEY}}') }}"
        inputs:
          fields:
          - id: MERAKI_KEY
            type: string
            label: Meraki Dashboard API key
            secret: true
          required:
            - MERAKI_KEY
        kind: cloud
        name: Meraki_API

    - name: Meraki API
      ansible.controller.credential:
        credential_type: Meraki_API
        description: ""
        inputs:
          MERAKI_KEY: "1234567890"
        name: 'Meraki API'
        organization: "Red Hat network organization"

    - name: Create a job-template - Network-Meraki-Get-Org-ID
      ansible.controller.job_template:
        name: "Network-Meraki-Get-Org-ID"
        organization: "Red Hat network organization"
        inventory: "Workshop Inventory"
        project: "Student Project"
        playbook: "cisco_meraki/get_orgID.yml"
        execution_environment: "Validated Network"
        credentials: 
         - 'Meraki API'
        state: "present"

    - name: Create a job-template - Network-Meraki-Create-Network
      ansible.controller.job_template:
        name: "Network-Meraki-Create-Network"
        organization: "Red Hat network organization"
        inventory: "Workshop Inventory"
        project: "Student Project"
        playbook: "cisco_meraki/create_network.yml"
        execution_environment: "Validated Network"
        credentials: 
         - 'Meraki API'
        state: "present"
        survey_enabled: yes
        survey_spec:
          {
            "description": "",
            "name": "",
            "spec":
              [
                {
                  "choices": "",
                  "default": "",
                  "max": 1024,
                  "min": 0,
                  "new_question": true,
                  "question_description": "Please provide your Organization ID",
                  "question_name": "Please provide your Organization ID",
                  "required": true,
                  "type": "textarea",
                  "variable": "org_id",
                },
                {
                  "choices": "",
                  "default": "",
                  "max": 1024,
                  "min": 0,
                  "new_question": true,
                  "question_description": "Please provide your Network name",
                  "question_name": "Please provide your Network name",
                  "required": true,
                  "type": "textarea",
                  "variable": "network_name",
                },
              ],
          }

    - name: Create a job-template - Network-Meraki-Remove-Network
      ansible.controller.job_template:
        name: "Network-Meraki-Remove-Network"
        organization: "Red Hat network organization"
        inventory: "Workshop Inventory"
        project: "Student Project"
        playbook: "cisco_meraki/remove_network.yml"
        execution_environment: "Validated Network"
        credentials: 
         - 'Meraki API'
        state: "present"
        survey_enabled: yes
        survey_spec:
          {
            "description": "",
            "name": "",
            "spec":
              [
                {
                  "choices": "",
                  "default": "",
                  "max": 1024,
                  "min": 0,
                  "new_question": true,
                  "question_description": "Please provide your Organization ID",
                  "question_name": "Please provide your Organization ID",
                  "required": true,
                  "type": "textarea",
                  "variable": "org_id",
                },
                {
                  "choices": "",
                  "default": "",
                  "max": 1024,
                  "min": 0,
                  "new_question": true,
                  "question_description": "Please provide your Network name",
                  "question_name": "Please provide your Network name",
                  "required": true,
                  "type": "textarea",
                  "variable": "network_name",
                },
              ],
          }


    - name: Create a job-template - Network-Meraki-Network-Meraki-Multi-SSID
      ansible.controller.job_template:
        name: "Network-Meraki-Multi-SSID"
        organization: "Red Hat network organization"
        inventory: "Workshop Inventory"
        project: "Student Project"
        playbook: "cisco_meraki/multiple_ssid.yml"
        execution_environment: "Validated Network"
        credentials: 
         - 'Meraki API'
        state: "present"
        extra_vars:
         org_id: ''
        ask_variables_on_launch: true