- name: Playbook to configure ansible controller
  hosts: localhost
  connection: local
  vars:
    user: "{{ username }}"

  environment:
    CONTROLLER_HOST: "ansible-1"
    CONTROLLER_USERNAME: "admin"
    CONTROLLER_PASSWORD: "{{ password }}"
    CONTROLLER_VERIFY_SSL: false

  tasks:
    - name: Create projects
      ansible.controller.project:
        name: Student Project
        organization: "Red Hat network organization"
        scm_url: "http://ansible-1:3000/gitea/network-demos-repo.git"
        scm_type: git
        allow_override: true
        state: present
        scm_update_on_launch: yes

    - name: Add group
      ansible.controller.group:
        name: cisco
        variables:
          ansible_connection: network_cli
          ansible_network_os: cisco.ios.ios
        inventory: "Workshop Inventory"
        state: present

    - name: Add group
      ansible.controller.group:
        name: arista
        variables:
          ansible_connection: network_cli
          ansible_network_os: arista.eos.eos
          ansible_become: "true"
          ansible_become_method: enable
        inventory: "Workshop Inventory"

    - name: Add group
      ansible.controller.group:
        name: juniper
        variables:
          ansible_connection: netconf
          ansible_network_os: junipernetworks.junos.junos
        inventory: "Workshop Inventory"
        state: present

    - name: Create Execution Environments
      ansible.controller.execution_environment:
        name: "Validated Network"
        image: registry.gitlab.com/redhatautomation/validated-network-ee:latest
        pull: missing

    - name: Gitea Credential Type
      ansible.controller.credential_type:
        injectors:
          extra_vars:
            email: "{{ email | default ('{{ email }}') }}"
            password: "{{ git_password | default ('{{ git_password }}') }}"
            username: "{{ username | default ('{{ username }}') }}"
            token: "{{ git_password | default ('{{ git_password }}') }}"
        inputs:
          fields:
            - id: username
              label: Username
              type: string
            - id: password
              label: Password
              secret: true
              type: string
            - id: email
              label: Email
              type: string
          required:
            - username
            - password
            - email
        kind: cloud
        name: Gitea Student

    - name: Gitea Credential
      ansible.controller.credential:
        credential_type: Gitea Student
        description: ""
        inputs:
          username: "gitea"
          password: "gitea"
          email: admin@example.com
        name: Gitea Credential
        organization: "Red Hat network organization"

    #Network Backups to GIT
    - name: Create a job-template - Network-Backups-Git
      ansible.controller.job_template:
        name: "Network-Backups-Git"
        organization: "Red Hat network organization"
        inventory: "Workshop Inventory"
        project: "Student Project"
        playbook: "network_backups_git/backups.yml"
        credentials:
          - "Workshop Credential"
          - "Gitea Credential"
          - "Controller Credential"
        execution_environment: "Validated Network"
        state: "present"

    # Network Compliance Dashboard   
    - name: Create a job-template - Network-Config
      ansible.controller.job_template:
        name: "Network-Config"
        organization: 'Red Hat network organization'
        inventory: "Workshop Inventory"
        project: "Student Project"
        playbook: "network_compliance_dashboard/config.yml"
        credentials:
          - "Workshop Credential"
        execution_environment: "Validated Network" 
        state: "present" 
    
    - name: Create a job-template - Network-Compliance-Dashboard
      ansible.controller.job_template:
        name: "Network-Compliance-Dashboard"
        organization: 'Red Hat network organization'
        inventory: "Workshop Inventory"
        project: "Student Project"
        playbook: "network_compliance_dashboard/network_report.yml"
        credentials:
          - "Workshop Credential"
        execution_environment: "network workshop execution environment" 
        state: "present"

    # This section includes Network-Check-Complisnce Demo
    - name: Create a job-template - Network-Check-Compliance
      ansible.controller.job_template:
        name: "Network-Check-Compliance"
        organization: 'Red Hat network organization'
        inventory: "Workshop Inventory"
        project: "Student Project"
        playbook: "network_compliance_checks_remediations/compliance.yml"
        credentials:
          - "Workshop Credential"
        execution_environment: "network workshop execution environment" 
        job_type: check
        state: "present" 
    
    - name: Create a job-template - Network-Run-Compliance
      ansible.controller.job_template:
        name: "Network-Run-Compliance"
        organization: 'Red Hat network organization'
        inventory: "Workshop Inventory"
        project: "Student Project"
        playbook: "network_compliance_checks_remediations/compliance.yml"
        credentials:
          - "Workshop Credential"
        execution_environment: "network workshop execution environment" 
        job_type: check
        state: "present" 

    - name: Create a workflow job template 
      ansible.controller.workflow_job_template:
        name: Network-Compliance-Workflow
        inventory: 'Workshop Inventory'
        organization: "Red Hat network organization"
        state: present
        survey_enabled: true
        survey:
            name: ''
            description: ''
            spec:
              - question_name: Which groups/devices to run checks against?
                type: multiselect
                variable: _group
                required: true
                default:  ''
                choices:
                  - cisco
                  - arista
                  - juniper
              - question_name: Please select the desired compliance roles?
                type: multiselect
                variable: tag
                required: true
                default: ''
                choices:
                  - logging
                  - snmp 
                  - ntp
                  - stig

    - name: Node Network-Run-Compliance
      ansible.controller.workflow_job_template_node:    
        identifier: Network-Run-Compliance
        workflow: 'Network-Compliance-Workflow'
        unified_job_template: Network-Run-Compliance
        organization: 'Red Hat network organization'
        state: present
        
    - name: Node Change Approval
      ansible.controller.workflow_job_template_node:    
        identifier: 'Change Approval'
        workflow_job_template: 'Network-Compliance-Workflow'
        organization: 'Red Hat network organization'
        approval_node: 
          name: 'Change Approval'
          timeout: 0
        state: present    

    - name: Node Change Approval
      ansible.controller.workflow_job_template_node:    
        identifier: 'Change Approval'
        workflow_job_template: 'Network-Compliance-Workflow'
        organization: 'Red Hat network organization'
        success_nodes: 
        - Network-Run-Compliance
        state: present    

    - name: Node Network-Check-Compliance
      ansible.controller.workflow_job_template_node:    
        identifier: Network-Check-Compliance
        workflow: 'Network-Compliance-Workflow'
        unified_job_template: Network-Check-Compliance
        organization: 'Red Hat network organization'
        success_nodes: 'Change Approval'
        state: present

# This section includes Scoped-config-management

    - name: Create a job-template - Network-Validated-Persist
      ansible.controller.job_template:
        name: "Network-Validated-Persist"
        organization: "Red Hat network organization"
        inventory: "Workshop Inventory"
        project: "Student Project"
        playbook: "scoped_configuration_management/persist.yml"
        credentials:
          - "Workshop Credential"
          - "Gitea Credential"
        execution_environment: "Validated Network"
        state: "present"

    - name: Create a job-template - Network-Validated-Deploy
      ansible.controller.job_template:
        name: "Network-Validated-Deploy"
        organization: "Red Hat network organization"
        inventory: "Workshop Inventory"
        project: "Student Project"
        playbook: "scoped_configuration_management/deploy.yml"
        credentials:
          - "Workshop Credential"
          - "Gitea Credential"
        execution_environment: "Validated Network"
        state: "present"

    - name: Create a job-template - Network-Validated-Detect
      ansible.controller.job_template:
        name: "Network-Validated-Detect"
        organization: "Red Hat network organization"
        inventory: "Workshop Inventory"
        project: "Student Project"
        playbook: "scoped_configuration_management/detect.yml"
        credentials:
          - "Workshop Credential"
          - "Gitea Credential"
        execution_environment: "Validated Network"
        state: "present"

    - name: Create a job-template - Network-Validated-Remediate
      ansible.controller.job_template:
        name: "Network-Validated-Remediate"
        organization: "Red Hat network organization"
        inventory: "Workshop Inventory"
        project: "Student Project"
        playbook: "scoped_configuration_management/remediate.yml"
        credentials:
          - "Workshop Credential"
          - "Gitea Credential"
        execution_environment: "Validated Network"
        state: "present"

# This section is for the completed network automation workshop 101 AAP Demo
    - name: Create a job-template - Backup network configurations
      ansible.controller.job_template:
        name: "Backup network configurations"
        organization: "Red Hat network organization"
        inventory: "Workshop Inventory"
        project: "Student Project"
        playbook: "completed_ansible_network_automation_workshop_101_demo/playbooks/network_backup.yml"
        credentials:
          - "Workshop Credential"
          - "Controller Credential"
        execution_environment: "Default execution environment"
        state: "present"

    - name: Create a job-template - Network Automation - Restore
      ansible.controller.job_template:
        name: "Network Automation - Restore"
        organization: "Red Hat network organization"
        inventory: "Workshop Inventory"
        project: "Student Project"
        playbook: "completed_ansible_network_automation_workshop_101_demo/playbooks/network_restore.yml"
        credentials:
          - "Workshop Credential"
        execution_environment: "Default execution environment"
        state: "present"

    - name: Create a job-template - Network-Banner
      ansible.controller.job_template:
        name: "Network-Banner"
        organization: "Red Hat network organization"
        inventory: "Workshop Inventory"
        project: "Student Project"
        playbook: "completed_ansible_network_automation_workshop_101_demo/playbooks/network_banner.yml"
        credentials:
          - "Workshop Credential"
        execution_environment: "Default execution environment"
        state: "present"

    - name: Enable host
      ansible.controller.host:
        name: backup-server
        state: present
        inventory: "Workshop Inventory" 
        enabled: true


      


    
