---
- name: convert configured ACLs to structured data
  hosts: cisco, juniper
  gather_facts: false
  tasks:
    - name: Use the ACLs resource module to gather the current config
      cisco.ios.ios_acls:
        state: gathered
      register: cisco_acls
      when: inventory_hostname in groups['cisco']

    - name: Use the ACLs resource module to gather the current config
      junipernetworks.junos.junos_acls:
        state: gathered
      register: juniper_acls
      when: inventory_hostname in groups['juniper']

    - name: Create inventory directory
      file:
       path: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}"
       state: directory

    - name: Write the Cisco ACL configuration to a file
      copy:
        content: "{{ {'cisco_acls': cisco_acls['gathered']} | to_nice_yaml }}"
        dest: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/acls.yaml"
      when: inventory_hostname in groups['cisco']

    - name: Write the Juniper ACL configuration to a file
      copy:
        content: "{{ {'juniper_acls': juniper_acls['gathered']} | to_nice_yaml }}"
        dest: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/acls.yaml"
      when: inventory_hostname in groups['juniper']