---
- name: Remediate configuration files from the resource modules
  hosts: network
  gather_facts: false

  tasks:
    - name: Network ACLs
      ansible.builtin.include_role:
        name: network.acls.run
      vars:
        operations:
          - name: remediate
        data_store:
          local: "{{ playbook_dir }}"
