#Dcloud
cat:
  hosts:
    198.18.1.31:
    198.18.1.32:
  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    ansible_user: developer
    ansible_password: C1sco12345